export function ToDouble(u:BigInt):number
export function ToDouble_1(u:number):number
export function ToDouble_2(u:number):number
export function ToDouble_3(s:string):number
export function ToDouble_4(s:number):number
export function ToDouble_5(s:number):number
export function ToDouble_6(i:BigInt):number
export function ToDouble_7(i:number):number
export function ToDouble_8(i:number):number
export function ToDouble_9(d:number):number
export function ToDouble_10<T0>(dt:number):T0
export function ToDouble_11<T0>(c:string):T0
export function ToDouble_12(b:number):number
export function ToDouble_13(b:boolean):number
export function ToSingle(u:BigInt):number
export function ToSingle_1(u:number):number
export function ToSingle_2(u:number):number
export function ToSingle_3(s:string):number
export function ToSingle_4(s:number):number
export function ToSingle_5(s:number):number
export function ToSingle_6(i:BigInt):number
export function ToSingle_7(i:number):number
export function ToSingle_8(i:number):number
export function ToSingle_9(d:number):number
export function ToSingle_10<T0>(dt:number):T0
export function ToSingle_11<T0>(c:string):T0
export function ToSingle_12(b:number):number
export function ToSingle_13(b:boolean):number
export function ToDateTime<T0>(u:BigInt):T0
export function ToDateTime_1<T0>(u:number):T0
export function ToDateTime_2<T0>(u:number):T0
export function ToDateTime_3(s:string):number
export function ToDateTime_4<T0>(s:number):T0
export function ToDateTime_5<T0>(s:number):T0
export function ToDateTime_6<T0>(i:BigInt):T0
export function ToDateTime_7<T0>(i:number):T0
export function ToDateTime_8<T0>(i:number):T0
export function ToDateTime_9<T0>(d:number):T0
export function ToDateTime_10(dt:number):number
export function ToDateTime_11<T0>(c:string):T0
export function ToDateTime_12<T0>(b:number):T0
export function ToDateTime_13<T0>(b:boolean):T0
export function ToUInt16(u:BigInt):number
export function ToUInt16_1(u:number):number
export function ToUInt16_2(u:number):number
export function ToUInt16_3(s:string):number
export function ToUInt16_4(s:number):number
export function ToUInt16_5(s:number):number
export function ToUInt16_6(i:BigInt):number
export function ToUInt16_7(i:number):number
export function ToUInt16_8(i:number):number
export function ToUInt16_9(d:number):number
export function ToUInt16_10<T0>(dt:number):T0
export function ToUInt16_11(c:string):number
export function ToUInt16_12(b:number):number
export function ToUInt16_13(b:boolean):number
export function ToUInt64(u:BigInt):BigInt
export function ToUInt64_1(u:number):BigInt
export function ToUInt64_2(u:number):BigInt
export function ToUInt64_3(s:string):BigInt
export function ToUInt64_4(s:number):BigInt
export function ToUInt64_5(s:number):BigInt
export function ToUInt64_6(i:BigInt):BigInt
export function ToUInt64_7(i:number):BigInt
export function ToUInt64_8(i:number):BigInt
export function ToUInt64_9(d:number):BigInt
export function ToUInt64_10<T0>(dt:number):T0
export function ToUInt64_11(c:string):BigInt
export function ToUInt64_12(b:number):BigInt
export function ToUInt64_13(b:boolean):BigInt
export function ToUInt32(u:BigInt):number
export function ToUInt32_1(u:number):number
export function ToUInt32_2(u:number):number
export function ToUInt32_3(s:string):number
export function ToUInt32_4(s:number):number
export function ToUInt32_5(s:number):number
export function ToUInt32_6(i:BigInt):number
export function ToUInt32_7(i:number):number
export function ToUInt32_8(i:number):number
export function ToUInt32_9(d:number):number
export function ToUInt32_10<T0>(dt:number):T0
export function ToUInt32_11(c:string):number
export function ToUInt32_12(b:number):number
export function ToUInt32_13(b:boolean):number
export function ToInt16(u:BigInt):number
export function ToInt16_1(u:number):number
export function ToInt16_2(u:number):number
export function ToInt16_3(s:string):number
export function ToInt16_4(s:number):number
export function ToInt16_5(s:number):number
export function ToInt16_6(i:BigInt):number
export function ToInt16_7(i:number):number
export function ToInt16_8(i:number):number
export function ToInt16_9(d:number):number
export function ToInt16_10<T0>(dt:number):T0
export function ToInt16_11(c:string):number
export function ToInt16_12(b:number):number
export function ToInt16_13(b:boolean):number
export function ToInt64(u:BigInt):BigInt
export function ToInt64_1(u:number):BigInt
export function ToInt64_2(u:number):BigInt
export function ToInt64_3(s:string):BigInt
export function ToInt64_4(s:number):BigInt
export function ToInt64_5(s:number):BigInt
export function ToInt64_6(i:BigInt):BigInt
export function ToInt64_7(i:number):BigInt
export function ToInt64_8(i:number):BigInt
export function ToInt64_9(d:number):BigInt
export function ToInt64_10<T0>(dt:number):T0
export function ToInt64_11(c:string):BigInt
export function ToInt64_12(b:number):BigInt
export function ToInt64_13(b:boolean):BigInt
export function ToInt32(u:BigInt):number
export function ToInt32_1(u:number):number
export function ToInt32_2(u:number):number
export function ToInt32_3(s:string):number
export function ToInt32_4(s:number):number
export function ToInt32_5(s:number):number
export function ToInt32_6(i:BigInt):number
export function ToInt32_7(i:number):number
export function ToInt32_8(i:number):number
export function ToInt32_9(d:number):number
export function ToInt32_10<T0>(dt:number):T0
export function ToInt32_11(c:string):number
export function ToInt32_12(b:number):number
export function ToInt32_13(b:boolean):number
export function ToChar(u:BigInt):string
export function ToChar_1(u:number):string
export function ToChar_2(u:number):string
export function ToChar_3(s:string):string
export function ToChar_4<T0>(s:number):T0
export function ToChar_5(s:number):string
export function ToChar_6(i:BigInt):string
export function ToChar_7(i:number):string
export function ToChar_8(i:number):string
export function ToChar_9<T0>(d:number):T0
export function ToChar_10<T0>(dt:number):T0
export function ToChar_11(c:string):string
export function ToChar_12(b:number):string
export function ToChar_13(b:boolean):string
export function ToSByte(u:BigInt):number
export function ToSByte_1(u:number):number
export function ToSByte_2(u:number):number
export function ToSByte_3(s:string):number
export function ToSByte_4(s:number):number
export function ToSByte_5(s:number):number
export function ToSByte_6(i:BigInt):number
export function ToSByte_7(i:number):number
export function ToSByte_8(i:number):number
export function ToSByte_9(d:number):number
export function ToSByte_10<T0>(dt:number):T0
export function ToSByte_11(c:string):number
export function ToSByte_12(b:number):number
export function ToSByte_13(b:boolean):number
export function ToByte(u:BigInt):number
export function ToByte_1(u:number):number
export function ToByte_2(u:number):number
export function ToByte_3(s:string):number
export function ToByte_4(s:number):number
export function ToByte_5(s:number):number
export function ToByte_6(i:BigInt):number
export function ToByte_7(i:number):number
export function ToByte_8(i:number):number
export function ToByte_9(d:number):number
export function ToByte_10<T0>(dt:number):T0
export function ToByte_11(c:string):number
export function ToByte_12(b:number):number
export function ToByte_13(b:boolean):number
export function ToBoolean(u:BigInt):boolean
export function ToBoolean_1(u:number):boolean
export function ToBoolean_2(u:number):boolean
export function ToBoolean_3(s:string):boolean
export function ToBoolean_4(s:number):boolean
export function ToBoolean_5(s:number):boolean
export function ToBoolean_6(i:BigInt):boolean
export function ToBoolean_7(i:number):boolean
export function ToBoolean_8(i:number):boolean
export function ToBoolean_9(d:number):boolean
export function ToBoolean_10<T0>(dt:number):T0
export function ToBoolean_11<T0>(c:string):T0
export function ToBoolean_12(b:number):boolean
export function ToBoolean_13(b:boolean):boolean
